# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44f6a192642dc61dc132405cc27d03ab6716e3a042e8abb59a17e79e66eec65a80f9daf99b0cb6643af01e44b1957f84478a4f877747047fb3e717e2e9cb07af

test:
  secret_key_base: 61f51674aa50c0b7ecd44214eefc94cf5d57864a53704cc5776f3f60157c23c21dcb069017a5df2fadd38e91f04b78f3fceadac95d9ac16eae39bd991af7ccb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
